# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('isOver', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('theme', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
        migrations.AddField(
            model_name='item',
            name='detail',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(max_length=255, null=True, upload_to='./resources'),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='thumbsDown',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='thumbsUp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_items', to='webapp.Event'),
        ),
    ]
