# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voter',
            new_name='Vote',
        ),
    ]
