# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20171128_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='voters',
        ),
    ]
