# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20171128_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_brought', to='webapp.Item')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_brought', to='webapp.Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='voter',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_voter', to='webapp.Item'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_voter', to='webapp.Profile'),
        ),
    ]
