# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20171128_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='item',
            name='thumbsDown',
        ),
        migrations.RemoveField(
            model_name='item',
            name='thumbsUp',
        ),
        migrations.AlterField(
            model_name='item',
            name='suggestedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_by', to='webapp.Profile'),
        ),
    ]
