# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20171130_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(default='./resources/jacquet.png', max_length=255, null=True, upload_to='./resources'),
        ),
    ]
