# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20171130_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='picture',
        ),
    ]
