# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 16:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_remove_item_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='suggestedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
